05. Валидации и Scope-методы
alexamy/thinknetica-rails pull request #10
Opened 2020-08-17 21:19 UTC by alexamy

1. Определите scope-методы:
для выбора правильных Ответов
Для выбора Тестов по уровню сложности:
- простой (нулевой или первый уровень),
- средний (со второго по четвёртый),
- сложный (с пятого и выше). Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания

2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях

3. Определите валидации данных:
- Наличие атрибутов title, body, email в соответствующих моделях
- Уровень Теста может быть только положительным целым числом
- Может существовать только один Тест с данным названием и уровнем
- У одного Вопроса может быть от 1-го до 4-х ответов.

2020-08-18 07:09 UTC, BubuntuClu requested changes

2020-08-18 07:09 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_answer_count
когда ты создаешь ответ, валидация вопроса будет отрабатывать?
+ отрабатывать она должна только при создании ответа.

2020-08-18 07:09 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_category, -> category_name do
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2020-08-18 07:09 UTC, BubuntuClu commented on db/migrate/20200817210207_add_unique_index_to_tests.rb
> +    add_index :tests, [:title, :level], unique: true
в модель тоже надо добавить это ограничение

2020-08-19 10:23 UTC, alexamy commented on db/migrate/20200817210207_add_unique_index_to_tests.rb
> +    add_index :tests, [:title, :level], unique: true
это не то? https://github.com/alexamy/thinknetica-rails/pull/10/files#diff-37551ba28e891d9dedb691f35f631d7aR8

2020-08-24 22:13 UTC, merged